name: Deploy-Staging-Production

on:
  workflow_dispatch:

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://yahoo.co.jp
    steps:
      - run: echo deploy staging
  
  deploy_production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://google.com
    steps:
      - run: echo deploy production